### ISSUE TITLE
NITRIC_AMPLIFY_AUTH_PATH not working

### ISSUE THREAD

**Issue by bls-lehoai** [nitrictech/amplify-secure-js#12]
Hi there. I am stuck at step 3:
"3. Ensure you have your API routes set up to store the secure cookies, see the API route example below."

I am using nuxt server middleware to host API and works well at localhost but when I publish aws it dont work.

From my understanding, this API has to host on the backend like lambda, right?

Please help, thanks.

**Comment by davemooreuws** [comment]
@bls-lehoai yes the production url base path (the backend) should be added to your environment variables. If you are deploying with nitric this url path will be displayed after deployment.

**Comment by davemooreuws** [comment]
Closed as question was answered.
