### ISSUE TITLE
Security concern: XSS vulnerability

### ISSUE THREAD

**Issue by gornostal** [nitrictech/amplify-secure-js#13]
### Issue

Does the `GET /api/auth` return access and refresh tokens in the response? It seems so. 
In that case, just like with the local storage, this solution is vulnerable to XSS.

### Steps

Imagine a following scenario

1. User installs a browser extension with a malware
2. User visits a website that uses this solution
3. The malware knows about this vulnerability and calls GET /api/auth
4. Now it has access to the access and refresh tokens

### Expected

1. User installs a browser extension with a malware
2. User visits a website that uses this solution
3. The malware can still call any APIs of the website, but it cannot steal the tokens

**Comment by davemooreuws** [comment]
Hi @gornostal ,

Thank you for your question.

The cookies are stored as HTTP-only secure cookies. HTTP-only cookies are designed to be inaccessible to client-side scripts, including malware running within a web browser. They can only be transmitted over HTTP(S) requests to the server.

However, yes the initial amplify auth does call the server to set this. There is not much we can do until Amplify adds more options.
This library prevents the storage of the tokens in local storage.

I will close this for now.
